#!/bin/sh
echo "🕵🏾‍♀️ Running pre-commit hooks"

echo "🔍 Running lint-staged"
npx lint-staged

echo "🔍 Running lint"
npx prettier --write .

echo "🏗️ Building the project"
npm run build

echo "🎉 pre-commit hooks completed 🎉"